### PR TITLE
update dat-ecosystem manifesto

### PR DESCRIPTION
**Pull request by serapath**
@cblgh 
@pfrazee 
@ninabreznik
@RangerMauve 
@zootella 
@Frando 
@dpaez 
@serapath

**Changes:**
1. remove Martin Heidegger from the consortium members as requested by him.
2. remove the need for meeting every 2 weeks and update voting mechanism accordingly
3. add rule for consortium members to quit the consortium.
4. add rule for inactive consortium members to become dormant indefinitely in voting contexts
   * but keep the option to re-activate themselves in the future

**Additionally:**
In the past, on `2021.01.11` we agreed on the [shared intent](https://github.com/dat-ecosystem/organization/blob/main/consortium/archive/2021.01.11%20_%20Intent%20for%20a%20Dat%20Ecosystem%20Manifesto.md) to have a manifesto. Not all goals expressed found their way into the manifesto yet and it might require another proposal to change that.

This proposal includes the goal to support projects (=dat ecosystem members) that **empower users**.

### CODE REVIEW

**Comment by martinheidegger** [comment]
👍 by me

**Review by RangerMauve — APPROVED** [review]
Mind removing me as well? I don't have capacity to contribute to this endeavor anymore.

**Comment by pfrazee** [comment]
Yeah unfortunately I've got to drop as well

**Comment by cblgh** [comment]
👍

**Comment by ninabreznik** [comment]
👍

**Comment by dpaez** [comment]
👍

**Comment by serapath** [comment]
👍

**Comment by zootella** [comment]
👍

**Comment by Frando** [comment]
:+1:

**Comment by serapath** [comment]
Thakn you everyone. Changes to the manifesto are now merged.

@martinheidegger, @pfrazee, @RangerMauve
:pray: I would like to thank you for your contributions to the dat-ecosystem and the consortium.
Although you decided to not be active in the consortium anymore, I hope you will stay active friends of the dat-ecosystem :heart: :slightly_smiling_face:

**Comment by serapath** [comment]
Thank you everyone. Changes to the manifesto are now merged.

@martinheidegger, @pfrazee, @RangerMauve
:pray: I would like to thank you for your contributions to the dat-ecosystem and the consortium.
Although you decided to not be active in the consortium anymore, I hope you will stay active friends of the dat-ecosystem :heart: :slightly_smiling_face:

**Pull request merged**
